### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by doabigcheese** [f00d4tehg0dz/starcitizen-server-status-plugin-for-elgato-streamdeck#2]
CIG changed the layout of their status page, the Plugin is not working anymore... only showing "updating"

**Comment by f00d4tehg0dz** [comment]
Thanks for the heads-up! I'll update this shortly!

**Comment by TheGreyDiamond** [comment]
Sadly still an issue...

**Comment by f00d4tehg0dz** [comment]
@doabigcheese @TheGreyDiamond  years later I have _finally_ updated this plugin. It'll be coming to the Elgato Marketplace soon as well. For now you can directly install it [here](https://github.com/f00d4tehg0dz/starcitizen-server-status-plugin-for-elgato-streamdeck/releases/download/2.0.1/com.f00d4tehg0dz.star-citizen-status.streamDeckPlugin)
